// generated by Fast Light User Interface Designer (fluid) version 1.0009

#include "Counter.H"

inline void Counter::cb_main_w_i(Fl_Window*, void*) {
  quit_cb();
}
void Counter::cb_main_w(Fl_Window* o, void* v) {
  ((Counter*)(o->user_data()))->cb_main_w_i(o,v);
}

inline void Counter::cb_command_i(Fl_Return_Button*, void*) {
  command_cb();
}
void Counter::cb_command(Fl_Return_Button* o, void* v) {
  ((Counter*)(o->parent()->user_data()))->cb_command_i(o,v);
}

Counter::Counter() {
  Fl_Window* w;
  { Fl_Window* o = main_w = new Fl_Window(421, 100, "Counter");
    w = o;
    o->callback((Fl_Callback*)cb_main_w, (void*)(this));
    { Fl_Value_Slider* o = progress = new Fl_Value_Slider(5, 20, 410, 30, "Progress:");
      o->type(3);
      o->color(7);
      o->labelfont(4);
      o->labelsize(18);
      o->maximum(100);
      o->step(0.1);
      o->textsize(14);
      o->textcolor(4);
      o->align(FL_ALIGN_TOP_LEFT);
      o->set_output();
    }
    { Fl_Return_Button* o = command = new Fl_Return_Button(155, 60, 125, 35, "START");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelfont(9);
      o->labelsize(18);
      o->labelcolor(4);
      o->callback((Fl_Callback*)cb_command);
    }
    o->end();
  }
}
